;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        apply-operation-to-number-at-point
        c-electric-delete-forward
        c-electric-paren
        c-electric-slash
        counsel-M-x
        crux-kill-whole-line
        crux-move-beginning-of-line
        easy-kill
        eval-last-sexp
        helm-M-x
        iy-go-to-char--command
        kill-region
        matlab-electric-comment
        mc-friendly/zap-up-to-char
        org-delete-char
        org-metaright
        org-self-insert-command
        prelude-move-beginning-of-line
        sp-backward-sexp
        sp-forward-sexp
        sp-rewrap-sexp
        sp-splice-sexp
        wdired-finish-edit
        wdired-previous-line
        yas-expand
        zop-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        hydra--digit-argument
        hydra-mc/mc/edit-beginnings-of-lines
        hydra-mc/mc/edit-beginnings-of-lines-and-exit
        hydra-mc/mc/edit-ends-of-lines-and-exit
        hydra-mc/mc/edit-lines-and-exit
        hydra-mc/mc/mark-all-like-this
        hydra-mc/mc/mark-next-like-this
        hydra-mc/mc/mark-previous-like-this
        hydra-mc/mc/skip-to-next-like-this
        hydra-region/mc/edit-beginnings-of-lines-and-exit
        hydra-region/mc/edit-lines-and-exit
        hydra-region/mc/mark-all-like-this-and-exit
        hydra-region/mc/mark-next-like-this
        hydra-region/mc/mark-previous-like-this
        hydra-region/mc/skip-to-next-like-this
        hydra-region/mc/skip-to-previous-like-this
        ivy-done
        repeat
        ))
